import { Routes, Route } from "react-router-dom";
import HomePage from "./HomePage";
import Template from "./Template";



function App() {
  const data = {
    german: {
      name: "Germany",
      topLevelDomain: [".de"],
      alpha2Code: "DE",
      alpha3Code: "DEU",
      callingCodes: ["49"],
      capital: "Berlin",
      altSpellings: [
        "DE",
        "Federal Republic of Germany",
        "Bundesrepublik Deutschland",
      ],
      subregion: "Central Europe",
      region: "Europe",
      population: 83240525,
      latlng: [51, 9],
      demonym: "German",
      area: 357114,
      gini: 31.9,
      timezones: ["UTC+01:00"],
      borders: ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
      nativeName: "Deutschland",
      numericCode: "276",
      flags: {
        svg: "https://flagcdn.com/de.svg",
        png: "https://flagcdn.com/w320/de.png",
      },
      currencies: [
        {
          code: "EUR",
          name: "Euro",
          symbol: "€",
        },
      ],
      languages: [
        {
          iso639_1: "de",
          iso639_2: "deu",
          name: "German",
          nativeName: "Deutsch",
        },
      ],
      translations: {
        br: "Alamagn",
        pt: "Alemanha",
        nl: "Duitsland",
        hr: "Njemačka",
        fa: "آلمان",
        de: "Deutschland",
        es: "Alemania",
        fr: "Allemagne",
        ja: "ドイツ",
        it: "Germania",
        hu: "Grúzia",
      },
      flag: "https://flagcdn.com/de.svg",
      regionalBlocs: [
        {
          acronym: "EU",
          name: "European Union",
        },
      ],
      cioc: "GER",
      independent: true,
    },
    usa: {
      name: "United States of America",
      topLevelDomain: [".us"],
      alpha2Code: "US",
      alpha3Code: "USA",
      callingCodes: ["1"],
      capital: "Washington, D.C.",
      altSpellings: ["US", "USA", "United States of America"],
      subregion: "Northern America",
      region: "Americas",
      population: 329484123,
      latlng: [38, -97],
      demonym: "American",
      area: 9629091,
      gini: 41.4,
      timezones: [
        "UTC-12:00",
        "UTC-11:00",
        "UTC-10:00",
        "UTC-09:00",
        "UTC-08:00",
        "UTC-07:00",
        "UTC-06:00",
        "UTC-05:00",
        "UTC-04:00",
        "UTC+10:00",
        "UTC+12:00",
      ],
      borders: ["CAN", "MEX"],
      nativeName: "United States",
      numericCode: "840",
      flags: {
        svg: "https://flagcdn.com/us.svg",
        png: "https://flagcdn.com/w320/us.png",
      },
      currencies: [
        {
          code: "USD",
          name: "United States dollar",
          symbol: "$",
        },
      ],
      languages: [
        {
          iso639_1: "en",
          iso639_2: "eng",
          name: "English",
          nativeName: "English",
        },
      ],
      translations: {
        br: "Stadoù-Unanet",
        pt: "Estados Unidos",
        nl: "Verenigde Staten",
        hr: "Sjedinjene Američke Države",
        fa: "ایالات متحده آمریکا",
        de: "Vereinigte Staaten von Amerika",
        es: "Estados Unidos",
        fr: "États-Unis",
        ja: "アメリカ合衆国",
        it: "Stati Uniti D'America",
        hu: "Amerikai Egyesült Államok",
      },
      flag: "https://flagcdn.com/us.svg",
      regionalBlocs: [
        {
          acronym: "NAFTA",
          name: "North American Free Trade Agreement",
          otherNames: [
            "Tratado de Libre Comercio de América del Norte",
            "Accord de Libre-échange Nord-Américain",
          ],
        },
      ],
      cioc: "USA",
      independent: true,
    },
    brazil: {
      name: "Brazil",
      topLevelDomain: [".br"],
      alpha2Code: "BR",
      alpha3Code: "BRA",
      callingCodes: ["55"],
      capital: "Brasília",
      altSpellings: [
        "BR",
        "Brasil",
        "Federative Republic of Brazil",
        "República Federativa do Brasil",
      ],
      subregion: "South America",
      region: "Americas",
      population: 212559409,
      latlng: [-10, -55],
      demonym: "Brazilian",
      area: 8515767,
      gini: 53.4,
      timezones: ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
      borders: [
        "ARG",
        "BOL",
        "COL",
        "FRA",
        "GUF",
        "GUY",
        "PRY",
        "PER",
        "SUR",
        "URY",
        "VEN",
      ],
      nativeName: "Brasil",
      numericCode: "076",
      flags: {
        svg: "https://flagcdn.com/br.svg",
        png: "https://flagcdn.com/w320/br.png",
      },
      currencies: [
        {
          code: "BRL",
          name: "Brazilian real",
          symbol: "R$",
        },
      ],
      languages: [
        {
          iso639_1: "pt",
          iso639_2: "por",
          name: "Portuguese",
          nativeName: "Português",
        },
      ],
      translations: {
        br: "Brazil",
        pt: "Brasil",
        nl: "Brazilië",
        hr: "Brazil",
        fa: "برزیل",
        de: "Brasilien",
        es: "Brasil",
        fr: "Brésil",
        ja: "ブラジル",
        it: "Brasile",
        hu: "Brazília",
      },
      flag: "https://flagcdn.com/br.svg",
      regionalBlocs: [
        {
          acronym: "USAN",
          name: "Union of South American Nations",
          otherAcronyms: ["UNASUR", "UNASUL", "UZAN"],
          otherNames: [
            "Unión de Naciones Suramericanas",
            "União de Nações Sul-Americanas",
            "Unie van Zuid-Amerikaanse Naties",
            "South American Union",
          ],
        },
      ],
      cioc: "BRA",
      independent: true,
    },
    afghanistan: {
      name: "Afghanistan",
      topLevelDomain: [".af"],
      alpha2Code: "AF",
      alpha3Code: "AFG",
      callingCodes: ["93"],
      capital: "Kabul",
      altSpellings: ["AF", "Afġānistān"],
      subregion: "Southern Asia",
      region: "Asia",
      population: 40218234,
      latlng: [33, 65],
      demonym: "Afghan",
      area: 652230,
      timezones: ["UTC+04:30"],
      borders: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
      nativeName: "افغانستان",
      numericCode: "004",
      flags: {
        svg: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
        png: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
      },
      currencies: [
        {
          code: "AFN",
          name: "Afghan afghani",
          symbol: "؋",
        },
      ],
      languages: [
        {
          iso639_1: "ps",
          iso639_2: "pus",
          name: "Pashto",
          nativeName: "پښتو",
        },
        {
          iso639_1: "uz",
          iso639_2: "uzb",
          name: "Uzbek",
          nativeName: "Oʻzbek",
        },
        {
          iso639_1: "tk",
          iso639_2: "tuk",
          name: "Turkmen",
          nativeName: "Türkmen",
        },
      ],
      translations: {
        br: "Afghanistan",
        pt: "Afeganistão",
        nl: "Afghanistan",
        hr: "Afganistan",
        fa: "افغانستان",
        de: "Afghanistan",
        es: "Afganistán",
        fr: "Afghanistan",
        ja: "アフガニスタン",
        it: "Afghanistan",
        hu: "Afganisztán",
      },
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
      regionalBlocs: [
        {
          acronym: "SAARC",
          name: "South Asian Association for Regional Cooperation",
        },
      ],
      cioc: "AFG",
      independent: true,
    },
    aland: {
      name: "Åland Islands",
      topLevelDomain: [".ax"],
      alpha2Code: "AX",
      alpha3Code: "ALA",
      callingCodes: ["358"],
      capital: "Mariehamn",
      altSpellings: ["AX", "Aaland", "Aland", "Ahvenanmaa"],
      subregion: "Northern Europe",
      region: "Europe",
      population: 28875,
      latlng: [60.116667, 19.9],
      demonym: "Ålandish",
      area: 1580,
      timezones: ["UTC+02:00"],
      nativeName: "Åland",
      numericCode: "248",
      flags: {
        svg: "https://flagcdn.com/ax.svg",
        png: "https://flagcdn.com/w320/ax.png",
      },
      currencies: [
        {
          code: "EUR",
          name: "Euro",
          symbol: "€",
        },
      ],
      languages: [
        {
          iso639_1: "sv",
          iso639_2: "swe",
          name: "Swedish",
          nativeName: "svenska",
        },
      ],
      translations: {
        br: "Åland",
        pt: "Ilhas de Aland",
        nl: "Ålandeilanden",
        hr: "Ålandski otoci",
        fa: "جزایر الند",
        de: "Åland",
        es: "Alandia",
        fr: "Åland",
        ja: "オーランド諸島",
        it: "Isole Aland",
        hu: "Åland-szigetek",
      },
      flag: "https://flagcdn.com/ax.svg",
      regionalBlocs: [
        {
          acronym: "EU",
          name: "European Union",
        },
      ],
      independent: false,
    },
    albania: {
      name: "Albania",
      topLevelDomain: [".al"],
      alpha2Code: "AL",
      alpha3Code: "ALB",
      callingCodes: ["355"],
      capital: "Tirana",
      altSpellings: ["AL", "Shqipëri", "Shqipëria", "Shqipnia"],
      subregion: "Southern Europe",
      region: "Europe",
      population: 2837743,
      latlng: [41, 20],
      demonym: "Albanian",
      area: 28748,
      gini: 33.2,
      timezones: ["UTC+01:00"],
      borders: ["MNE", "GRC", "MKD", "UNK"],
      nativeName: "Shqipëria",
      numericCode: "008",
      flags: {
        svg: "https://flagcdn.com/al.svg",
        png: "https://flagcdn.com/w320/al.png",
      },
      currencies: [
        {
          code: "ALL",
          name: "Albanian lek",
          symbol: "L",
        },
      ],
      languages: [
        {
          iso639_1: "sq",
          iso639_2: "sqi",
          name: "Albanian",
          nativeName: "Shqip",
        },
      ],
      translations: {
        br: "Albania",
        pt: "Albânia",
        nl: "Albanië",
        hr: "Albanija",
        fa: "آلبانی",
        de: "Albanien",
        es: "Albania",
        fr: "Albanie",
        ja: "アルバニア",
        it: "Albania",
        hu: "Albánia",
      },
      flag: "https://flagcdn.com/al.svg",
      regionalBlocs: [
        {
          acronym: "CEFTA",
          name: "Central European Free Trade Agreement",
        },
      ],
      cioc: "ALB",
      independent: true,
    },
    iceland: {
      name: "Iceland",
      topLevelDomain: [".is"],
      alpha2Code: "IS",
      alpha3Code: "ISL",
      callingCodes: ["354"],
      capital: "Reykjavík",
      altSpellings: ["IS", "Island", "Republic of Iceland", "Lýðveldið Ísland"],
      subregion: "Northern Europe",
      region: "Europe",
      population: 366425,
      latlng: [65, -18],
      demonym: "Icelander",
      area: 103000,
      gini: 26.1,
      timezones: ["UTC"],
      nativeName: "Ísland",
      numericCode: "352",
      flags: {
        svg: "https://flagcdn.com/is.svg",
        png: "https://flagcdn.com/w320/is.png",
      },
      currencies: [
        {
          code: "ISK",
          name: "Icelandic króna",
          symbol: "kr",
        },
      ],
      languages: [
        {
          iso639_1: "is",
          iso639_2: "isl",
          name: "Icelandic",
          nativeName: "Íslenska",
        },
      ],
      translations: {
        br: "Island",
        pt: "Islândia",
        nl: "IJsland",
        hr: "Island",
        fa: "ایسلند",
        de: "Island",
        es: "Islandia",
        fr: "Islande",
        ja: "アイスランド",
        it: "Islanda",
        hu: "Izland",
      },
      flag: "https://flagcdn.com/is.svg",
      regionalBlocs: [
        {
          acronym: "EFTA",
          name: "European Free Trade Association",
        },
      ],
      cioc: "ISL",
      independent: true,
    },
    algeria: {
      name: "Algeria",
      topLevelDomain: [".dz"],
      alpha2Code: "DZ",
      alpha3Code: "DZA",
      callingCodes: ["213"],
      capital: "Algiers",
      altSpellings: ["DZ", "Dzayer", "Algérie"],
      subregion: "Northern Africa",
      region: "Africa",
      population: 44700000,
      latlng: [28, 3],
      demonym: "Algerian",
      area: 2381741,
      gini: 27.6,
      timezones: ["UTC+01:00"],
      borders: ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"],
      nativeName: "الجزائر",
      numericCode: "012",
      flags: {
        svg: "https://flagcdn.com/dz.svg",
        png: "https://flagcdn.com/w320/dz.png",
      },
      currencies: [
        {
          code: "DZD",
          name: "Algerian dinar",
          symbol: "د.ج",
        },
      ],
      languages: [
        {
          iso639_1: "ar",
          iso639_2: "ara",
          name: "Arabic",
          nativeName: "العربية",
        },
      ],
      translations: {
        br: "Aljeria",
        pt: "Argélia",
        nl: "Algerije",
        hr: "Alžir",
        fa: "الجزایر",
        de: "Algerien",
        es: "Argelia",
        fr: "Algérie",
        ja: "アルジェリア",
        it: "Algeria",
        hu: "Algéria",
      },
      flag: "https://flagcdn.com/dz.svg",
      regionalBlocs: [
        {
          acronym: "AU",
          name: "African Union",
          otherNames: [
            "الاتحاد الأفريقي",
            "Union africaine",
            "União Africana",
            "Unión Africana",
            "Umoja wa Afrika",
          ],
        },
        {
          acronym: "AL",
          name: "Arab League",
          otherNames: [
            "جامعة الدول العربية",
            "Jāmiʻat ad-Duwal al-ʻArabīyah",
            "League of Arab States",
          ],
        },
      ],
      cioc: "ALG",
      independent: true,
    },
  };
  return (
    <>
      <Routes>
        <Route path="/" element={<HomePage data={data} />} />
        <Route path="Germany" element={<Template info={data} Country="german"/>} />
        <Route path="USA" element={<Template info={data} Country="usa"/>} />
        <Route path="Brazil" element={<Template info={data} Country="brazil"/>} />
        <Route path="IceLand" element={<Template info={data} Country="iceland"/>} />
        <Route path="Afghanistan" element={<Template info={data} Country="afghanistan"/>} />
        <Route path="Aland" element={<Template info={data} Country="aland"/>} />
        <Route path="Albania" element={<Template info={data} Country="albania"/>} />
        <Route path="Algeria" element={<Template info={data} Country="algeria"/>} />
        
      </Routes>
    </>
  );
}

export default App;
